server:
  port: 0

spring:
  application:
    name: data-source-manager
  profiles:
    active:
      default
  datasource:
    url: jdbc:postgresql://localhost:5432/webplatform
    username: ohdsi
    password: ohdsi
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        default_schema: datasourcemanager
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    schemas: ${spring.jpa.properties.hibernate.default_schema}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8090/me

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.ohdsi.datasourcemanager: DEBUG

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    enabled: false